### ISSUE TITLE
What is the difference between auth.session and auth.currentSession?

### ISSUE THREAD

**Issue by sarperdag** [supabase/supabase-swift#554]
I can't seem to understand what the difference is between 

```
let client = SupabaseClient(...)
let session = try await client.auth.session
```

and 
`client.auth.currentSession`

When I do a signout, looks like currentSession is nilled but client.auth.session is not. It's still live and it's got a refreshToken etc that I can use to refresh the session if I need to. Shouldn't calling signout() be invalidating client.auth.session too like it invalidates client.auth.currentSession?

I'm confused... Which one should I be referring to?

**Comment by grdsdev** [comment]
Hi @sarperdag 

The `session` property is an async property that checks if the current session is valid, if not, refreshes it before returning, so it is guaranteed to be valid (not expired).

The `currentSession` is sync, and just returns the session stored in local storage (keychain by default).

The doc comments explains those behaviors:

```swift
/// Returns the session, refreshing it if necessary.
///
/// If no session can be found, a ``AuthError/sessionNotFound`` error is thrown.
public var session: Session

/// Returns the current session, if any.
///
/// The session returned by this property may be expired. Use ``session`` for a session that is guaranteed to be valid.
public var currentSession: Session?
```

Understood that, after `signOut`, both properties should be cleared, `currentSession` should return `nil`, and `session`, should throw a `AuthError.sessionNotFound` error, since you mention that isn't happening, I'm going to investigate as it may be a bug.

Answering your question on which one should you be referring to.

It depends on which information you're extracting from the session, use `session` when you need to use the access token or you need up-to-date data. Use `currentSession` if you don't care about the up-do-date data. Note that `session` can take more time to return, as if session expired (or is about to expire), a new HTTP request will fired for refreshing the session.

Hope this clarified things a bit for you, let me know if you need any other thing.

I'll take a look at signOut issue for now, thanks.

**Comment by sarperdag** [comment]
Thank you for the clarification @grdsdev. And yup, I just tried again with the commit (eab7a4a7a494cfdf354ecd16373bbc05d4a0977f) on the main branch and it looks like signout() still has the issue I mentioned above.

**Comment by grdsdev** [comment]
which version of the library are you using? and how are you calling `signOut`?

I've just added [an integration test](https://github.com/supabase/supabase-swift/issues/554) for signOut, and it is working fine.

**Comment by grdsdev** [comment]
Closing this, if you still facing this issue, feel free to reopen it.
